### ISSUE TITLE
Error could not resolve when using Vite

### ISSUE THREAD

**Issue by lamualfa** [id-kemo/responsive-ant-menu#7]
![image](https://user-images.githubusercontent.com/39755201/125329698-01255c00-e370-11eb-86b1-5b1fc927d959.png)

I got the error above when using Vite.

I think the error occurs because the `lodash.throttle` was set as a `peerDependendencies` in [here](https://github.com/itskemo/responsive-ant-menu/blob/36cb270d05c3682c06afd4face0cd941fa660784/package.json#L49). The solution is move it to `dependencies` field instead `peerDependencies`. The semantic version concept will guaranteed that dependencies with difference version from conflict.

**Comment by itskemo** [comment]
@lamualfa Although I don't have space to test it with Vite Ill move the lodash.throttle under deps since it's direct dependency anyway. Thanks for reporting.

EDIT: I see you went ahead and created couple of PRs, thanks for that.
